import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
// import StarsCanvas from './components/main/StarBackground'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'VJTI Social Groups',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar/> */}
        {/* <StarsCanvas /> */}
        {children}
        </body>
    </html>
  )
}
